-- Run these SQL queries in your Supabase dashboard:
-- Go to https://supabase.com/dashboard/project/iijgdnfbvlfczmanhekg/sql

-- 1. Create posts table
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author TEXT NOT NULL,
  avatar TEXT NOT NULL,
  posted TEXT NOT NULL,
  image TEXT NOT NULL,
  description TEXT NOT NULL,
  since TEXT NOT NULL,
  platform TEXT NOT NULL,
  likes INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  followers INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create testimonials table
CREATE TABLE testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create services table
CREATE TABLE services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  icon TEXT NOT NULL,
  color TEXT NOT NULL,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Insert sample data
INSERT INTO posts (author, avatar, posted, image, description, since, platform, likes, shares, followers) VALUES
('Sarah Chen', 'https://picsum.photos/seed/avatar1/40/40', '2 hours ago', 'https://picsum.photos/seed/news/400/300', 'Just launched our new design system. Excited to share it with the community!', 'Mar 4, 2026', 'Creative Studio', 234, 45, 1250),
('Alex Rivera', 'https://picsum.photos/seed/avatar2/40/40', '5 hours ago', 'https://picsum.photos/seed/project2/400/300', 'Working on something amazing. Can''t wait to show you all the details!', 'Mar 4, 2026', 'Personal', 189, 23, 890),
('Jordan Kim', 'https://picsum.photos/seed/avatar3/40/40', '1 day ago', 'https://picsum.photos/seed/design3/400/300', 'New UI concept for a mobile app. What do you think about the color palette?', 'Mar 3, 2026', 'Design', 456, 78, 2340),
('Maya Patel', 'https://picsum.photos/seed/avatar4/40/40', '2 days ago', 'https://picsum.photos/seed/tech4/400/300', 'Finally finished the backend API. Documentation is next on the list!', 'Mar 2, 2026', 'Development', 312, 56, 1560),
('Chris Johnson', 'https://picsum.photos/seed/avatar5/40/40', '3 days ago', 'https://picsum.photos/seed/art5/400/300', 'Experimenting with new illustration techniques. This one was inspired by nature.', 'Mar 1, 2026', 'Art', 567, 89, 3210),
('Casey Adams', 'https://picsum.photos/seed/avatar6/40/40', '12 hours ago', 'https://picsum.photos/seed/podcast/400/300', 'New episode discussing trends in creative technology. Listen now!', 'Mar 4, 2026', 'Podcast', 234, 56, 0);

INSERT INTO testimonials (name, role, content, rating) VALUES
('Sarah Johnson', 'CEO, TechStart', 'Exceptional work! Delivered our project on time and exceeded expectations. Highly recommend.', 5);

INSERT INTO services (title, description, icon, color, display_order) VALUES
('Web Development', 'Building responsive and performant web applications with modern technologies', 'Code', 'text-blue-400', 0),
('UI/UX Design', 'Creating intuitive and beautiful user interfaces that delight users', 'Palette', 'text-purple-400', 1),
('Mobile Apps', 'Developing cross-platform mobile applications for iOS and Android', 'Smartphone', 'text-green-400', 2);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

-- 6. Create policies for public access
CREATE POLICY "Enable read access for all users" ON posts FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON posts FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON testimonials FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON testimonials FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON services FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON services FOR INSERT WITH CHECK (true);
