-- Additional SQL queries to add projects and shop products tables
-- Run these in your Supabase SQL Editor after the initial setup

-- 7. Create projects table
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL,
  category TEXT NOT NULL,
  technologies TEXT[], -- Array of technologies used
  github_url TEXT,
  live_url TEXT,
  featured BOOLEAN DEFAULT FALSE,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Create shop_products table
CREATE TABLE shop_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image TEXT NOT NULL,
  category TEXT NOT NULL,
  in_stock BOOLEAN DEFAULT TRUE,
  featured BOOLEAN DEFAULT FALSE,
  tags TEXT[], -- Array of tags
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Insert sample projects
INSERT INTO projects (title, description, image, category, technologies, github_url, live_url, featured, display_order) VALUES
('E-Commerce Platform', 'Modern e-commerce solution with real-time inventory management', 'https://picsum.photos/seed/project1/400/300', 'Web Development', ARRAY['React', 'Node.js', 'PostgreSQL', 'Stripe'], 'https://github.com/example/ecommerce', 'https://example-ecommerce.com', TRUE, 0),
('Task Management App', 'Collaborative task management tool with real-time updates', 'https://picsum.photos/seed/project2/400/300', 'Mobile App', ARRAY['React Native', 'Firebase', 'Redux'], 'https://github.com/example/tasks', 'https://example-tasks.com', TRUE, 1),
('AI Content Generator', 'AI-powered content generation platform', 'https://picsum.photos/seed/project3/400/300', 'AI/ML', ARRAY['Python', 'TensorFlow', 'React', 'OpenAI'], 'https://github.com/example/ai-content', 'https://example-ai.com', FALSE, 2),
('Portfolio Website', 'Personal portfolio with dynamic content management', 'https://picsum.photos/seed/project4/400/300', 'Web Design', ARRAY['Next.js', 'Tailwind CSS', 'Framer Motion'], 'https://github.com/example/portfolio', 'https://example-portfolio.com', FALSE, 3);

-- 10. Insert sample shop products
INSERT INTO shop_products (name, description, price, image, category, in_stock, featured, tags, display_order) VALUES
('Premium UI Kit', 'Complete UI component library with 50+ components', 49.99, 'https://picsum.photos/seed/product1/300/300', 'Digital Products', TRUE, TRUE, ARRAY['UI', 'React', 'Components'], 0),
('Mobile App Template', 'React Native template for e-commerce apps', 79.99, 'https://picsum.photos/seed/product2/300/300', 'Templates', TRUE, TRUE, ARRAY['Mobile', 'React Native', 'Template'], 1),
('Design System Guide', 'Comprehensive guide to building design systems', 29.99, 'https://picsum.photos/seed/product3/300/300', 'Books', TRUE, FALSE, ARRAY['Design', 'Guide', 'PDF'], 2),
('Icon Pack Pro', '1000+ premium icons for modern applications', 19.99, 'https://picsum.photos/seed/product4/300/300', 'Assets', TRUE, FALSE, ARRAY['Icons', 'SVG', 'Graphics'], 3),
('Code Theme Bundle', 'Dark/light themes for popular code editors', 14.99, 'https://picsum.photos/seed/product5/300/300', 'Tools', TRUE, FALSE, ARRAY['Theme', 'VS Code', 'Sublime'], 4);

-- 11. Enable RLS for new tables
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE shop_products ENABLE ROW LEVEL SECURITY;

-- 12. Create policies for new tables
CREATE POLICY "Enable read access for all users" ON projects FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON projects FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON shop_products FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON shop_products FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON shop_products FOR UPDATE USING (true);

-- 13. Create function for incrementing likes (if not exists)
CREATE OR REPLACE FUNCTION like_post(post_id BIGINT)
RETURNS BIGINT AS $$
BEGIN
  UPDATE posts 
  SET likes = likes + 1, updated_at = NOW()
  WHERE id = post_id;
  
  RETURN (SELECT likes FROM posts WHERE id = post_id);
END;
$$ LANGUAGE plpgsql;

-- 14. Create function for incrementing shares
CREATE OR REPLACE FUNCTION share_post(post_id BIGINT)
RETURNS BIGINT AS $$
BEGIN
  UPDATE posts 
  SET shares = shares + 1, updated_at = NOW()
  WHERE id = post_id;
  
  RETURN (SELECT shares FROM posts WHERE id = post_id);
END;
$$ LANGUAGE plpgsql;
